---
- name: Install zookeeper
  apt:
    pkg: zookeeperd
    state: present
    update_cache: true

- name: Setup zoo.cfg
  template:
    src: zoo.cfg.j2
    dest: /etc/zookeeper/conf/zoo.cfg
    mode: 644
  notify:
    - Restart zookeeper

- name: Setup myid
  template:
    src: myid.j2
    dest: /etc/zookeeper/conf/myid
    mode: 644
  notify:
    - Restart zookeeper

- name: Start zookeeper service
  service:
    name: zookeeper
    state: started

- meta: flush_handlers
